-- ============================================================================
-- TABLA PARA SOLICITUDES DE ELIMINACIÓN DE CUENTA
-- ============================================================================
-- Esta tabla almacena las solicitudes de eliminación de cuenta con un período
-- de gracia de 60 días por cuestiones legales y de seguridad.
-- ============================================================================

-- Crear ENUM para estado de solicitud de eliminación
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_solicitud_eliminacion') THEN
    CREATE TYPE public.estado_solicitud_eliminacion AS ENUM (
      'pendiente',
      'cancelada',
      'procesada'
    );
  END IF;
END $$;

-- Crear tabla de solicitudes de eliminación
CREATE TABLE IF NOT EXISTS public.solicitudes_eliminacion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  fecha_solicitud timestamptz NOT NULL DEFAULT now(),
  fecha_eliminacion timestamptz NOT NULL,
  estado public.estado_solicitud_eliminacion NOT NULL DEFAULT 'pendiente',
  motivo text,
  procesada_at timestamptz,
  cancelada_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fecha_eliminacion_futura CHECK (fecha_eliminacion > fecha_solicitud)
);

-- Trigger para updated_at
CREATE TRIGGER set_timestamp_solicitudes_eliminacion
BEFORE UPDATE ON public.solicitudes_eliminacion
FOR EACH ROW
EXECUTE FUNCTION public.set_current_timestamp_updated_at();

-- Índices
CREATE INDEX IF NOT EXISTS idx_solicitudes_eliminacion_usuario 
  ON public.solicitudes_eliminacion(usuario_id);

CREATE INDEX IF NOT EXISTS idx_solicitudes_eliminacion_estado 
  ON public.solicitudes_eliminacion(estado);

CREATE INDEX IF NOT EXISTS idx_solicitudes_eliminacion_fecha_eliminacion 
  ON public.solicitudes_eliminacion(fecha_eliminacion) 
  WHERE estado = 'pendiente';

-- Índice único parcial para garantizar que un usuario solo tenga una solicitud pendiente
CREATE UNIQUE INDEX IF NOT EXISTS idx_solicitudes_eliminacion_usuario_pendiente 
  ON public.solicitudes_eliminacion(usuario_id) 
  WHERE estado = 'pendiente';

-- Comentarios
COMMENT ON TABLE public.solicitudes_eliminacion IS 
'Tabla que almacena las solicitudes de eliminación de cuenta con período de gracia de 60 días';

COMMENT ON COLUMN public.solicitudes_eliminacion.fecha_eliminacion IS 
'Fecha programada para la eliminación definitiva de la cuenta (60 días después de la solicitud)';

COMMENT ON COLUMN public.solicitudes_eliminacion.estado IS 
'Estado de la solicitud: pendiente (aún no procesada), cancelada (usuario canceló), procesada (ya eliminada)';

-- Habilitar RLS
ALTER TABLE public.solicitudes_eliminacion ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
DROP POLICY IF EXISTS "Users can read own deletion request" ON public.solicitudes_eliminacion;
CREATE POLICY "Users can read own deletion request" ON public.solicitudes_eliminacion
  FOR SELECT
  USING (auth.role() = 'authenticated' AND auth.uid() = usuario_id);

DROP POLICY IF EXISTS "Users can create own deletion request" ON public.solicitudes_eliminacion;
CREATE POLICY "Users can create own deletion request" ON public.solicitudes_eliminacion
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = usuario_id);

DROP POLICY IF EXISTS "Users can cancel own deletion request" ON public.solicitudes_eliminacion;
CREATE POLICY "Users can cancel own deletion request" ON public.solicitudes_eliminacion
  FOR UPDATE
  USING (auth.role() = 'authenticated' AND auth.uid() = usuario_id AND estado = 'pendiente')
  WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = usuario_id AND estado = 'cancelada');

-- Política para administradores (pueden leer y procesar todas las solicitudes)
DROP POLICY IF EXISTS "Admins can manage all deletion requests" ON public.solicitudes_eliminacion;
CREATE POLICY "Admins can manage all deletion requests" ON public.solicitudes_eliminacion
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE id = auth.uid() 
      AND email = 'admin@ofisi.ar'
    )
  );
